//Admin pages export
export {default as AdminHome} from '../components/Admin/index'
export {default as AdminLogin} from '../components/Admin/Auth'
export {default as NewDepartment} from '../components/Admin/Create/Department'
export {default as NewLab} from '../components/Admin/Create/Lab'
export {default as NewMachine} from '../components/Admin/Create/Machine'
export {default as NewWorkshop} from '../components/Admin/Create/Workshop'
export {default as NewWorkshopType} from '../components/Admin/Create/WorkshopType'
export {default as UpdateDepartment} from '../components/Admin/Update/Department'
export {default as UpdateEmployee} from '../components/Admin/Update/Employee'
export {default as UpdateGuest} from '../components/Admin/Update/Guest'
export {default as UpdateLab} from '../components/Admin/Update/Lab'
export {default as UpdateMachine} from '../components/Admin/Update/Machine'
export {default as UpdateWorkshop} from '../components/Admin/Update/Workshop'
export {default as UpdateWorkshopType} from '../components/Admin/Update/WorkshopType'
export {default as ReadDepartments} from '../components/Admin/Read/Department'
export {default as ReadEmployees} from '../components/Admin/Read/Employee/EmployeeList'
export {default as ReadGuests} from '../components/Admin/Read/Guest/GuestList'
export {default as ReadLabs} from '../components/Admin/Read/Lab'
export {default as ReadMachines} from '../components/Admin/Read/Machine'
export {default as ReadReservations} from '../components/Admin/Read/Reservation/ReservationList'
export {default as ReadWorkshops} from '../components/Admin/Read/Workshop'
export {default as ReadWorkshopTypes} from '../components/Admin/Read/WorkshopType'

//Shared pages export
export {default as EmployeeDetails} from '../components/Shared/ResourceDetails/Employee'
export {default as LabDetails} from '../components/Shared/ResourceDetails/Lab'
export {default as MachineDetails} from '../components/Shared/ResourceDetails/Machine'
export {default as ReservationDetails} from './Shared/ResourceDetails/Reservation'
export {default as WorkshopDetails} from '../components/Shared/ResourceDetails/Workshop'

//Main pages export 
export {default as HomePage} from '../components/Main/Home'
export {default as Login} from '../components/Main/Auth/Login'
export {default as Register} from '../components/Main/Auth/Register'
export {default as RequestNewPassword} from '../components/Main/Auth/RequestNewPassword'
export {default as ResetPassword} from '../components/Main/Auth/ResetPassword'
export {default as PrivacyPolicy} from '../components/Main/PrivacyPolicy'
export {default as ChangePassword} from '../components/Main/Profile/ChangePassword'
export {default as DeleteAccount} from '../components/Main/Profile/DeleteAccount'
export {default as MyReservations} from './Main/Profile/Reservations/'
export {default as UpdateProfile} from '../components/Main/Profile/UpdateProfile'
export {default as ResourceSearch} from '../components/Main/ReasourceSearch'
export {default as Employees} from '../components/Main/Resources/Employees'
export {default as Labs} from '../components/Main/Resources/Labs'
export {default as Machines} from '../components/Main/Resources/Machines'
export {default as Workshops} from '../components/Main/Resources/Workshops'
export {default as ReservationSurvey} from './Main/Profile/Reservations/ReservationSurvey'